import daisyui from 'daisyui'

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
      {
        roze: {
          "primary": "#f472b6",
          "primary-content": "#ffffff",
          "secondary": "#ec4899",
          "secondary-content": "#ffffff",
          "accent": "#fb7185",
          "accent-content": "#ffffff",
          "neutral": "#831843",
          "neutral-content": "#fce7f3",
          "base-100": "#fff0f6",
          "base-200": "#fce7f3",
          "base-300": "#fbcfe8",
          "base-content": "#831843",
          "info": "#f9a8d4",
          "success": "#f472b6",
          "warning": "#fb923c",
          "error": "#be123c",
        },
      },
    ],
  },
}