import daisyui from 'daisyui'

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      "acid",
      "aqua",
      "autumn",
      "black",
      "bumblebee",
      "business",
      "cmyk",
      "coffee",
      "corporate",
      "cupcake",
      "cyberpunk",
      "dark",
      "dim",
      "dracula",
      "emerald",
      "fantasy",
      "forest",
      "garden",
      "halloween",
      "lemonade",
      "light",
      "lofi",
      "luxury",
      "night",
      "nord",
      "pastel",
      "retro",
      { roze: {
        "primary": "#f472b6",
        "primary-content": "#ffffff",
        "secondary": "#ec4899",
        "secondary-content": "#ffffff",
        "accent": "#fb7185",
        "accent-content": "#ffffff",
        "neutral": "#831843",
        "neutral-content": "#fce7f3",
        "base-100": "#fff0f6",
        "base-200": "#fce7f3",
        "base-300": "#fbcfe8",
        "base-content": "#831843",
        "info": "#f9a8d4",
        "success": "#f472b6",
        "warning": "#fb923c",
        "error": "#be123c",
      }},
      "sunset",
      "synthwave",
      "valentine",
      "wireframe",
      "winter",
    ],
  },
}
