export const THEMES = [
  {
    name: "light",
    label: "Light",
    colors: ["#ffffff", "#5a67d8", "#8b5cf6", "#1a202c"],
  },
  {
    name: "dark",
    label: "Dark",
    colors: ["#1f2937", "#8b5cf6", "#ec4899", "#1a202c"],
  },
  {
    name: "cupcake",
    label: "Cupcake",
    colors: ["#f5f5f4", "#65c3c8", "#ef9fbc", "#291334"],
  },
  {
    name: "forest",
    label: "Forest",
    colors: ["#1f1d1d", "#3ebc96", "#70c217", "#e2e8f0"],
  },
  {
    name: "bumblebee",
    label: "Bumblebee",
    colors: ["#ffffff", "#f8e36f", "#f0d50c", "#1c1917"],
  },
  {
    name: "emerald",
    label: "Emerald",
    colors: ["#ffffff", "#66cc8a", "#3b82f6", "#1e3a8a"],
  },
  {
    name: "corporate",
    label: "Corporate",
    colors: ["#ffffff", "#4b6bfb", "#7b92b2", "#1d232a"],
  },
  {
    name: "synthwave",
    label: "Synthwave",
    colors: ["#2d1b69", "#e779c1", "#58c7f3", "#f8f8f2"],
  },
  {
    name: "retro",
    label: "Retro",
    colors: ["#e4d8b4", "#ea6962", "#6aaa64", "#282425"],
  },
  {
    name: "cyberpunk",
    label: "Cyberpunk",
    colors: ["#ffee00", "#ff7598", "#75d1f0", "#1a103d"],
  },
  {
    name: "valentine",
    label: "Valentine",
    colors: ["#f0d6e8", "#e96d7b", "#a991f7", "#37243c"],
  },
  {
    name: "halloween",
    label: "Halloween",
    colors: ["#0d0d0d", "#ff7800", "#006400", "#ffffff"],
  },
  {
    name: "garden",
    label: "Garden",
    colors: ["#e9e7e7", "#ec4899", "#16a34a", "#374151"],
  },

  {
    name: "aqua",
    label: "Aqua",
    colors: ["#193549", "#4cd4e3", "#9059ff", "#f8d766"],
  },
  {
    name: "lofi",
    label: "Lofi",
    colors: ["#0f0f0f", "#1a1919", "#232323", "#2c2c2c"],
  },
  {
    name: "pastel",
    label: "Pastel",
    colors: ["#f7f3f5", "#d1c1d7", "#a1e3d8", "#4a98f1"],
  },
  {
    name: "fantasy",
    label: "Fantasy",
    colors: ["#ffe7d6", "#a21caf", "#3b82f6", "#f59e0b"],
  },
  {
    name: "wireframe",
    label: "Wireframe",
    colors: ["#e6e6e6", "#b3b3b3", "#b3b3b3", "#888888"],
  },
  {
    name: "black",
    label: "Black",
    colors: ["#000000", "#191919", "#313131", "#4a4a4a"],
  },
  {
    name: "luxury",
    label: "Luxury",
    colors: ["#171618", "#1e293b", "#94589c", "#d4a85a"],
  },
  {
    name: "dracula",
    label: "Dracula",
    colors: ["#282a36", "#ff79c6", "#bd93f9", "#f8f8f2"],
  },
  {
    name: "cmyk",
    label: "CMYK",
    colors: ["#f0f0f0", "#0891b2", "#ec4899", "#facc15"],
  },
  {
    name: "autumn",
    label: "Autumn",
    colors: ["#f2f2f2", "#8c1f11", "#f28c18", "#6f4930"],
  },
  {
    name: "business",
    label: "Business",
    colors: ["#f5f5f5", "#1e40af", "#3b82f6", "#f97316"],
  },
  {
    name: "acid",
    label: "Acid",
    colors: ["#110e0e", "#ff00f2", "#ff7a00", "#99ff01"],
  },
  {
    name: "lemonade",
    label: "Lemonade",
    colors: ["#ffffff", "#67e8f9", "#f5d742", "#2c3333"],
  },
  {
    name: "night",
    label: "Night",
    colors: ["#0f172a", "#38bdf8", "#818cf8", "#e2e8f0"],
  },
  {
    name: "coffee",
    label: "Coffee",
    colors: ["#20161f", "#dd9866", "#497174", "#eeeeee"],
  },
  {
    name: "winter",
    label: "Winter",
    colors: ["#ffffff", "#0284c7", "#d946ef", "#0f172a"],
  },
  {
    name: "dim",
    label: "Dim",
    colors: ["#1c1c27", "#10b981", "#ff5a5f", "#0f172a"],
  },
  {
    name: "nord",
    label: "Nord",
    colors: ["#eceff4", "#5e81ac", "#81a1c1", "#3b4252"],
  },
  {
    name: "sunset",
    label: "Sunset",
    colors: ["#1e293b", "#f5734c", "#ec4899", "#ffffff"],
  },
];


export const COUNTRIES = [
{ code:"AF", name:"Afghanistan", flag:"🇦🇫"},
{ code:"AL", name:"Albania", flag:"🇦🇱"},
{ code:"DZ", name:"Algeria", flag:"🇩🇿"},
{ code:"AD", name:"Andorra", flag:"🇦🇩"},
{ code:"AO", name:"Angola", flag:"🇦🇴"},
{ code:"AG", name:"Antigua and Barbuda", flag:"🇦🇬"},
{ code:"AR", name:"Argentina", flag:"🇦🇷"},
{ code:"AM", name:"Armenia", flag:"🇦🇲"},
{ code:"AU", name:"Australia", flag:"🇦🇺"},
{ code:"AT", name:"Austria", flag:"🇦🇹"},
{ code:"AZ", name:"Azerbaijan", flag:"🇦🇿"},
{ code:"BS", name:"Bahamas", flag:"🇧🇸"},
{ code:"BH", name:"Bahrain", flag:"🇧🇭"},
{ code:"BD", name:"Bangladesh", flag:"🇧🇩"},
{ code:"BB", name:"Barbados", flag:"🇧🇧"},
{ code:"BY", name:"Belarus", flag:"🇧🇾"},
{ code:"BE", name:"Belgium", flag:"🇧🇪"},
{ code:"BZ", name:"Belize", flag:"🇧🇿"},
{ code:"BJ", name:"Benin", flag:"🇧🇯"},
{ code:"BT", name:"Bhutan", flag:"🇧🇹"},
{ code:"BO", name:"Bolivia", flag:"🇧🇴"},
{ code:"BA", name:"Bosnia and Herzegovina", flag:"🇧🇦"},
{ code:"BW", name:"Botswana", flag:"🇧🇼"},
{ code:"BR", name:"Brazil", flag:"🇧🇷"},
{ code:"BN", name:"Brunei", flag:"🇧🇳"},
{ code:"BG", name:"Bulgaria", flag:"🇧🇬"},
{ code:"BF", name:"Burkina Faso", flag:"🇧🇫"},
{ code:"BI", name:"Burundi", flag:"🇧🇮"},
{ code:"KH", name:"Cambodia", flag:"🇰🇭"},
{ code:"CM", name:"Cameroon", flag:"🇨🇲"},
{ code:"CA", name:"Canada", flag:"🇨🇦"},
{ code:"CV", name:"Cape Verde", flag:"🇨🇻"},
{ code:"CF", name:"Central African Republic", flag:"🇨🇫"},
{ code:"TD", name:"Chad", flag:"🇹🇩"},
{ code:"CL", name:"Chile", flag:"🇨🇱"},
{ code:"CN", name:"China", flag:"🇨🇳"},
{ code:"CO", name:"Colombia", flag:"🇨🇴"},
{ code:"KM", name:"Comoros", flag:"🇰🇲"},
{ code:"CD", name:"Congo (DRC)", flag:"🇨🇩"},
{ code:"CG", name:"Congo (Republic)", flag:"🇨🇬"},
{ code:"CR", name:"Costa Rica", flag:"🇨🇷"},
{ code:"HR", name:"Croatia", flag:"🇭🇷"},
{ code:"CU", name:"Cuba", flag:"🇨🇺"},
{ code:"CY", name:"Cyprus", flag:"🇨🇾"},
{ code:"CZ", name:"Czech Republic", flag:"🇨🇿"},
{ code:"DK", name:"Denmark", flag:"🇩🇰"},
{ code:"DJ", name:"Djibouti", flag:"🇩🇯"},
{ code:"DM", name:"Dominica", flag:"🇩🇲"},
{ code:"DO", name:"Dominican Republic", flag:"🇩🇴"},
{ code:"EC", name:"Ecuador", flag:"🇪🇨"},
{ code:"EG", name:"Egypt", flag:"🇪🇬"},
{ code:"SV", name:"El Salvador", flag:"🇸🇻"},
{ code:"GQ", name:"Equatorial Guinea", flag:"🇬🇶"},
{ code:"ER", name:"Eritrea", flag:"🇪🇷"},
{ code:"EE", name:"Estonia", flag:"🇪🇪"},
{ code:"SZ", name:"Eswatini", flag:"🇸🇿"},
{ code:"ET", name:"Ethiopia", flag:"🇪🇹"},
{ code:"FJ", name:"Fiji", flag:"🇫🇯"},
{ code:"FI", name:"Finland", flag:"🇫🇮"},
{ code:"FR", name:"France", flag:"🇫🇷"},
{ code:"GA", name:"Gabon", flag:"🇬🇦"},
{ code:"GM", name:"Gambia", flag:"🇬🇲"},
{ code:"GE", name:"Georgia", flag:"🇬🇪"},
{ code:"DE", name:"Germany", flag:"🇩🇪"},
{ code:"GH", name:"Ghana", flag:"🇬🇭"},
{ code:"GR", name:"Greece", flag:"🇬🇷"},
{ code:"GD", name:"Grenada", flag:"🇬🇩"},
{ code:"GT", name:"Guatemala", flag:"🇬🇹"},
{ code:"GN", name:"Guinea", flag:"🇬🇳"},
{ code:"GW", name:"Guinea-Bissau", flag:"🇬🇼"},
{ code:"GY", name:"Guyana", flag:"🇬🇾"},
{ code:"HT", name:"Haiti", flag:"🇭🇹"},
{ code:"HN", name:"Honduras", flag:"🇭🇳"},
{ code:"HU", name:"Hungary", flag:"🇭🇺"},
{ code:"IS", name:"Iceland", flag:"🇮🇸"},
{ code:"IN", name:"India", flag:"🇮🇳"},
{ code:"ID", name:"Indonesia", flag:"🇮🇩"},
{ code:"IR", name:"Iran", flag:"🇮🇷"},
{ code:"IQ", name:"Iraq", flag:"🇮🇶"},
{ code:"IE", name:"Ireland", flag:"🇮🇪"},
{ code:"IL", name:"Israel", flag:"🇮🇱"},
{ code:"IT", name:"Italy", flag:"🇮🇹"},
{ code:"JM", name:"Jamaica", flag:"🇯🇲"},
{ code:"JP", name:"Japan", flag:"🇯🇵"},
{ code:"JO", name:"Jordan", flag:"🇯🇴"},
{ code:"KZ", name:"Kazakhstan", flag:"🇰🇿"},
{ code:"KE", name:"Kenya", flag:"🇰🇪"},
{ code:"KI", name:"Kiribati", flag:"🇰🇮"},
{ code:"KR", name:"South Korea", flag:"🇰🇷"},
{ code:"KW", name:"Kuwait", flag:"🇰🇼"},
{ code:"KG", name:"Kyrgyzstan", flag:"🇰🇬"},
{ code:"LA", name:"Laos", flag:"🇱🇦"},
{ code:"LV", name:"Latvia", flag:"🇱🇻"},
{ code:"LB", name:"Lebanon", flag:"🇱🇧"},
{ code:"LS", name:"Lesotho", flag:"🇱🇸"},
{ code:"LR", name:"Liberia", flag:"🇱🇷"},
{ code:"LY", name:"Libya", flag:"🇱🇾"},
{ code:"LI", name:"Liechtenstein", flag:"🇱🇮"},
{ code:"LT", name:"Lithuania", flag:"🇱🇹"},
{ code:"LU", name:"Luxembourg", flag:"🇱🇺"},
{ code:"MG", name:"Madagascar", flag:"🇲🇬"},
{ code:"MW", name:"Malawi", flag:"🇲🇼"},
{ code:"MY", name:"Malaysia", flag:"🇲🇾"},
{ code:"MV", name:"Maldives", flag:"🇲🇻"},
{ code:"ML", name:"Mali", flag:"🇲🇱"},
{ code:"MT", name:"Malta", flag:"🇲🇹"},
{ code:"MH", name:"Marshall Islands", flag:"🇲🇭"},
{ code:"MR", name:"Mauritania", flag:"🇲🇷"},
{ code:"MU", name:"Mauritius", flag:"🇲🇺"},
{ code:"MX", name:"Mexico", flag:"🇲🇽"},
{ code:"FM", name:"Micronesia", flag:"🇫🇲"},
{ code:"MD", name:"Moldova", flag:"🇲🇩"},
{ code:"MC", name:"Monaco", flag:"🇲🇨"},
{ code:"MN", name:"Mongolia", flag:"🇲🇳"},
{ code:"ME", name:"Montenegro", flag:"🇲🇪"},
{ code:"MA", name:"Morocco", flag:"🇲🇦"},
{ code:"MZ", name:"Mozambique", flag:"🇲🇿"},
{ code:"MM", name:"Myanmar", flag:"🇲🇲"},
{ code:"NA", name:"Namibia", flag:"🇳🇦"},
{ code:"NR", name:"Nauru", flag:"🇳🇷"},
{ code:"NP", name:"Nepal", flag:"🇳🇵"},
{ code:"NL", name:"Netherlands", flag:"🇳🇱"},
{ code:"NZ", name:"New Zealand", flag:"🇳🇿"},
{ code:"NI", name:"Nicaragua", flag:"🇳🇮"},
{ code:"NE", name:"Niger", flag:"🇳🇪"},
{ code:"NG", name:"Nigeria", flag:"🇳🇬"},
{ code:"MK", name:"North Macedonia", flag:"🇲🇰"},
{ code:"NO", name:"Norway", flag:"🇳🇴"},
{ code:"OM", name:"Oman", flag:"🇴🇲"},
{ code:"PK", name:"Pakistan", flag:"🇵🇰"},
{ code:"PW", name:"Palau", flag:"🇵🇼"},
{ code:"PA", name:"Panama", flag:"🇵🇦"},
{ code:"PG", name:"Papua New Guinea", flag:"🇵🇬"},
{ code:"PY", name:"Paraguay", flag:"🇵🇾"},
{ code:"PE", name:"Peru", flag:"🇵🇪"},
{ code:"PH", name:"Philippines", flag:"🇵🇭"},
{ code:"PL", name:"Poland", flag:"🇵🇱"},
{ code:"PT", name:"Portugal", flag:"🇵🇹"},
{ code:"QA", name:"Qatar", flag:"🇶🇦"},
{ code:"RO", name:"Romania", flag:"🇷🇴"},
{ code:"RU", name:"Russia", flag:"🇷🇺"},
{ code:"RW", name:"Rwanda", flag:"🇷🇼"},
{ code:"KN", name:"Saint Kitts and Nevis", flag:"🇰🇳"},
{ code:"LC", name:"Saint Lucia", flag:"🇱🇨"},
{ code:"VC", name:"Saint Vincent and the Grenadines", flag:"🇻🇨"},
{ code:"WS", name:"Samoa", flag:"🇼🇸"},
{ code:"SM", name:"San Marino", flag:"🇸🇲"},
{ code:"ST", name:"Sao Tome and Principe", flag:"🇸🇹"},
{ code:"SA", name:"Saudi Arabia", flag:"🇸🇦"},
{ code:"SN", name:"Senegal", flag:"🇸🇳"},
{ code:"RS", name:"Serbia", flag:"🇷🇸"},
{ code:"SC", name:"Seychelles", flag:"🇸🇨"},
{ code:"SL", name:"Sierra Leone", flag:"🇸🇱"},
{ code:"SG", name:"Singapore", flag:"🇸🇬"},
{ code:"SK", name:"Slovakia", flag:"🇸🇰"},
{ code:"SI", name:"Slovenia", flag:"🇸🇮"},
{ code:"SB", name:"Solomon Islands", flag:"🇸🇧"},
{ code:"SO", name:"Somalia", flag:"🇸🇴"},
{ code:"ZA", name:"South Africa", flag:"🇿🇦"},
{ code:"ES", name:"Spain", flag:"🇪🇸"},
{ code:"LK", name:"Sri Lanka", flag:"🇱🇰"},
{ code:"SD", name:"Sudan", flag:"🇸🇩"},
{ code:"SR", name:"Suriname", flag:"🇸🇷"},
{ code:"SE", name:"Sweden", flag:"🇸🇪"},
{ code:"CH", name:"Switzerland", flag:"🇨🇭"},
{ code:"SY", name:"Syria", flag:"🇸🇾"},
{ code:"TW", name:"Taiwan", flag:"🇹🇼"},
{ code:"TJ", name:"Tajikistan", flag:"🇹🇯"},
{ code:"TZ", name:"Tanzania", flag:"🇹🇿"},
{ code:"TH", name:"Thailand", flag:"🇹🇭"},
{ code:"TL", name:"Timor-Leste", flag:"🇹🇱"},
{ code:"TG", name:"Togo", flag:"🇹🇬"},
{ code:"TO", name:"Tonga", flag:"🇹🇴"},
{ code:"TT", name:"Trinidad and Tobago", flag:"🇹🇹"},
{ code:"TN", name:"Tunisia", flag:"🇹🇳"},
{ code:"TR", name:"Turkey", flag:"🇹🇷"},
{ code:"TM", name:"Turkmenistan", flag:"🇹🇲"},
{ code:"TV", name:"Tuvalu", flag:"🇹🇻"},
{ code:"UG", name:"Uganda", flag:"🇺🇬"},
{ code:"UA", name:"Ukraine", flag:"🇺🇦"},
{ code:"AE", name:"United Arab Emirates", flag:"🇦🇪"},
{ code:"GB", name:"United Kingdom", flag:"🇬🇧"},
{ code:"US", name:"United States", flag:"🇺🇸"},
{ code:"UY", name:"Uruguay", flag:"🇺🇾"},
{ code:"UZ", name:"Uzbekistan", flag:"🇺🇿"},
{ code:"VU", name:"Vanuatu", flag:"🇻🇺"},
{ code:"VA", name:"Vatican City", flag:"🇻🇦"},
{ code:"VE", name:"Venezuela", flag:"🇻🇪"},
{ code:"VN", name:"Vietnam", flag:"🇻🇳"},
{ code:"YE", name:"Yemen", flag:"🇾🇪"},
{ code:"ZM", name:"Zambia", flag:"🇿🇲"},
{ code:"ZW", name:"Zimbabwe", flag:"🇿🇼"}
];